title: BLOG | BLT
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://blacklovertech.in" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Janarthaan # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a Freelance developer . Always hungry to keep learning. # add description
social-twitter: blacklovertech
social-facebook: blacklovertech
social-github: blacklovertech
social-linkedin: blacklovertech
social-email: help@blacklovertech.in

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: markdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
